### ISSUE TITLE
Add IRC networks we use to humans.txt

### ISSUE THREAD

**Issue by lol768** [korobi/Web#180]

**Comment by lol768** [comment]
@bionicrm Yeah, I'm not sure how obvious that is to people though. I was thinking we could perhaps try something like this:

```
    lol768 - backend developer
        Twitter: @lol768
        GitHub: https://github.com/lol768/
        IRC: EsperNet, Freenode, ...
```

**Comment by bionicrm** [comment]
Personally I don't see the need for networks they're on (I go on Freenode only when I need help with something whose support channel is there), however I'd be interested to hear your reasoning.

**Comment by Zarthus** [comment]
those that don't want their networks displayed don't need to do it.

**Comment by lol768** [comment]
@bionicrm Then just list EsperNet, if it's your main network? I don't see anything that would tell users as to which network you normally use - Korobi isn't tied to EsperNet.

**Comment by bendem** [comment]
I honestly don't care about what's in humans.txt as long as my nick is in.
