### ISSUE TITLE
Make Web repo public

### ISSUE THREAD

**Issue by kashike** [korobi/Web#191]
- [x] @bendem
- [x] @kashike
- [x] @lol768
- [x] @Zarthus
- [x] @jamierocks 
- [x] @bionicrm 

todo:
- [x] remove any private information from issues
- [x] ensure no API keys are in the repo, regenerate those that are, and make them configurable options
- [x] pick license
- [x] get a security@korobi.io email address
- [x] Security page/RDP
- [x] https://github.com/korobi/Web/issues/114
- [x] CONTRIBUTING.md
- [x] Document branch prefixes
- [x] Fix auth header
- [x] remove `reviewed for release` label

**Comment by lol768** [comment]
\o/
