### ISSUE TITLE
Investigate StyleCI

### ISSUE THREAD

**Issue by lol768** [korobi/Web#208]
@korobi/deciders

**Comment by Zarthus** [comment]
what does it offer that Travis does not?

**Comment by bendem** [comment]
From what I understand, StyleCI's sole purpose is to check (and fix?) code style. https://styleci.readme.io/docs/fixers

**Comment by Zarthus** [comment]
But we do not have a coding style. - we just have this .php_cs file with a few rules that travis already checks for.

**Comment by bendem** [comment]
This? https://gist.github.com/bendem/fbae3fe48373359c48d5

**Comment by lol768** [comment]
Discussed in IRC, doesn't seem suitable in its current state.
