### ISSUE TITLE
Symfony 3.0

### ISSUE THREAD

**Issue by kashike** [korobi/Web#39]
Symfony 3.0 is scheduled to be released in November 2015.

http://symfony.com/blog/symfony-3-0-the-roadmap
https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md
### Dependency compatibility:
- [ ] [doctrine/mongodb](https://packagist.org/packages/doctrine/mongodb)
- [ ] [doctrine/mongodb-odm](https://packagist.org/packages/doctrine/mongodb-odm)
- [ ] [doctrine/mongodb-odm-bundle](https://packagist.org/packages/doctrine/mongodb-odm-bundle)
- [ ] [doctrine/doctrine-fixtures-bundle](https://packagist.org/packages/doctrine/doctrine-fixtures-bundle)
- [ ] [twig/extensions](https://packagist.org/packages/twig/extensions)
- [ ] [symfony/assetic-bundle](https://packagist.org/packages/symfony/assetic-bundle)
- [ ] [symfony/swiftmailer-bundle](https://packagist.org/packages/symfony/swiftmailer-bundle)
- [ ] [symfony/monolog-bundle](https://packagist.org/packages/symfony/monolog-bundle)
- [ ] [sensio/distribution-bundle](https://packagist.org/packages/sensio/distribution-bundle)
- [ ] [sensio/framework-extra-bundle](https://packagist.org/packages/sensio/framework-extra-bundle)
- [ ] [incenteev/composer-parameter-handler](https://packagist.org/packages/incenteev/composer-parameter-handler)
- [ ] [friendsofsymfony/user-bundle](https://packagist.org/packages/friendsofsymfony/user-bundle)
- [ ] [hwi/oauth-bundle](https://packagist.org/packages/hwi/oauth-bundle)
- [x] [guzzlehttp/guzzle](https://packagist.org/packages/guzzlehttp/guzzle)
- [x] [knplabs/github-api](https://packagist.org/packages/knplabs/github-api)
- [ ] [salavert/time-ago-in-words](https://packagist.org/packages/salavert/time-ago-in-words)
- [ ] [nelmio/security-bundle](https://packagist.org/packages/nelmio/security-bundle)
- [x] [crodas/influx-php](https://packagist.org/packages/crodas/influx-php)
- [x] [enygma/yubikey](https://packagist.org/packages/enygma/yubikey)

**Comment by HamidDarash** [comment]
Hi everyone
Symfony I 've got this problem in the authentication by wsse :

exception: [{message: "A Token was not found in the TokenStorage.",…}]
0: {message: "A Token was not found in the TokenStorage.",…}
class: "Symfony\Component\Security\Core\Exception\AuthenticationCredentialsNotFoundException"
message: "A Token was not found in the TokenStorage."
trace: [{namespace: "", short_class: "", class: "", type: "", function: "",…},…]
message: "Internal Server Error"
please help me.

**Comment by Zarthus** [comment]
You're at the wrong place buddy.
