### ISSUE TITLE
Add "external" error pages

### ISSUE THREAD

**Issue by kashike** [korobi/Web#58]
Add external error pages (403, 404, 500) that do not use any external or generated resources (in-line css, only required components to display standard pages), and store in `web/`.

(ref https://github.com/korobi/Web/issues/57)

**Comment by Zarthus** [comment]
@lol768, @kashike: Can this be closed?

**Comment by lol768** [comment]
@Zarthus I don't see any external error pages in https://github.com/korobi/Web/tree/master/web

**Comment by Zarthus** [comment]
both issues referencing this were closed, hence the question

**Comment by kashike** [comment]
There are no external pages yet, so no
